version: '3'

services: 
    app:
        build: .
        ports: 
            - "9000:9000"
        command: npm start
        environment: 
            - PEER_PATH=/chat
            - PEER_PORT=9000